/*
 * USERS action types
 */

export const GET_USERS__START = 'GET_USERS__START';
export const GET_USERS__SUCCESS = 'GET_USERS__SUCCESS';
export const GET_USERS__ERROR = 'GET_USERS__ERROR';
export const UPDATE_USERS__PHOTO_START = 'UPDATE_USERS__PHOTO_START';
export const UPDATE_USERS__PHOTO_SUCCESS = 'UPDATE_USERS__PHOTO_SUCCESS';
export const UPDATE_USERS__PHOTO_FAILURE = 'UPDATE_USERS__PHOTO_FAILURE';
